# VGG16 Model on cifar10 Dataset

#### Importing necessary libraries

In [1]:
from keras.layers import Convolution2D,MaxPooling2D,Dropout,Dense,Flatten, GlobalAveragePooling2D
from keras import models,losses,optimizers
from keras.preprocessing.image import ImageDataGenerator
from keras.applications import InceptionV3,VGG16,resnet50
from keras.models import Model

Using TensorFlow backend.


#### Loading the dataset

In [2]:
n_classes = 10
from tensorflow.keras.datasets import cifar10
(X_train,y_train),(X_test,y_test) = cifar10.load_data()
#Converting y to categorical
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
y_train = ohe.fit_transform(y_train).toarray().astype(int)

In [3]:
n_train = X_train.shape[0]
n_test = X_test.shape[0]

In [4]:
print( X_train.shape, y_train.shape,  X_test.shape, y_test.shape )

(50000, 32, 32, 3) (50000, 10) (10000, 32, 32, 3) (10000, 1)


#### Model Building
    - Importing the model
    - Adding few layers on top of pretrained model
    - Making the VGG16 Layers untrainable
    - Compiling the model
    - Summary of the model
    - Fitting the model to train images

In [7]:
from keras.applications import VGG16

In [8]:
base = VGG16(include_top = False,weights='imagenet',input_shape = (32,32,3))
model = models.Sequential()
model.add(base)
model.add(Flatten())
model.add(Dense(4096, activation='relu', name='Dense_Intermediate'))
model.add(Dropout(0.5, name='Dropout_Regularization'))
model.add(Dense(10, activation='softmax', name='Output'))

In [9]:
for cnnlayer in model.layers[0].layers:
    cnnlayer.trainable = False
model.layers[0].trainable = False

In [10]:
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [11]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
vgg16 (Model)                (None, 1, 1, 512)         14714688  
_________________________________________________________________
flatten_1 (Flatten)          (None, 512)               0         
_________________________________________________________________
Dense_Intermediate (Dense)   (None, 4096)              2101248   
_________________________________________________________________
Dropout_Regularization (Drop (None, 4096)              0         
_________________________________________________________________
Output (Dense)               (None, 10)                40970     
Total params: 16,856,906
Trainable params: 2,142,218
Non-trainable params: 14,714,688
_________________________________________________________________


In [12]:
model.fit(X_train,y_train,epochs=10,batch_size=100)

Epoch 1/10
50000/50000 [==============================] - 283s 6ms/step - loss: 2.8689 - accuracy: 0.5045
Epoch 2/10
50000/50000 [==============================] - 286s 6ms/step - loss: 1.2414 - accuracy: 0.5880
Epoch 3/10
50000/50000 [==============================] - 296s 6ms/step - loss: 1.1895 - accuracy: 0.6080
Epoch 4/10
50000/50000 [==============================] - 310s 6ms/step - loss: 1.1631 - accuracy: 0.6161
Epoch 5/10
50000/50000 [==============================] - 311s 6ms/step - loss: 1.1711 - accuracy: 0.6183
Epoch 6/10
50000/50000 [==============================] - 288s 6ms/step - loss: 1.1413 - accuracy: 0.6296
Epoch 7/10
50000/50000 [==============================] - 290s 6ms/step - loss: 1.1176 - accuracy: 0.6389
Epoch 8/10
50000/50000 [==============================] - 295s 6ms/step - loss: 1.0576 - accuracy: 0.6543
Epoch 9/10
50000/50000 [==============================] - 299s 6ms/step - loss: 1.0542 - accuracy: 0.6597
Epoch 10/10
50000/50000 [=====================

#### Fine tuning
    - Unfreezing last 4 layers of VGG16 model
    - Refitting the model

In [21]:
for layer in base.layers[:-4]:
    layer.trainable = False
for layer in base.layers[-4:]:
    layer.trainable = True
for layer in base.layers:
    print(layer, layer.trainable)

<keras.engine.input_layer.InputLayer object at 0x00000246D5C58C08> False
<keras.layers.convolutional.Conv2D object at 0x00000246D59544C8> False
<keras.layers.convolutional.Conv2D object at 0x00000246D5938648> False
<keras.layers.pooling.MaxPooling2D object at 0x00000246D5937A48> False
<keras.layers.convolutional.Conv2D object at 0x00000246D5952688> False
<keras.layers.convolutional.Conv2D object at 0x00000246D5FF3988> False
<keras.layers.pooling.MaxPooling2D object at 0x00000246D5FF7688> False
<keras.layers.convolutional.Conv2D object at 0x00000246D5FFC308> False
<keras.layers.convolutional.Conv2D object at 0x00000246D5FFEE48> False
<keras.layers.convolutional.Conv2D object at 0x00000246D6002B48> False
<keras.layers.pooling.MaxPooling2D object at 0x00000246D600A0C8> False
<keras.layers.convolutional.Conv2D object at 0x00000246D600AE48> False
<keras.layers.convolutional.Conv2D object at 0x00000246D60129C8> False
<keras.layers.convolutional.Conv2D object at 0x00000246D60136C8> False
<ker

In [22]:
model.fit(X_train,y_train,epochs=10,batch_size=100)

Epoch 1/10
50000/50000 [==============================] - 346s 7ms/step - loss: 1.0066 - accuracy: 0.6770
Epoch 2/10
50000/50000 [==============================] - 293s 6ms/step - loss: 0.9665 - accuracy: 0.6869
Epoch 3/10
50000/50000 [==============================] - 291s 6ms/step - loss: 0.9482 - accuracy: 0.6948
Epoch 4/10
50000/50000 [==============================] - 291s 6ms/step - loss: 0.9197 - accuracy: 0.7021
Epoch 5/10
50000/50000 [==============================] - 309s 6ms/step - loss: 0.9015 - accuracy: 0.7095
Epoch 6/10
50000/50000 [==============================] - 286s 6ms/step - loss: 0.8812 - accuracy: 0.7176
Epoch 7/10
50000/50000 [==============================] - 294s 6ms/step - loss: 0.8617 - accuracy: 0.7219
Epoch 8/10
50000/50000 [==============================] - 285s 6ms/step - loss: 0.8300 - accuracy: 0.7315
Epoch 9/10
50000/50000 [==============================] - 285s 6ms/step - loss: 0.8157 - accuracy: 0.7400
Epoch 10/10
50000/50000 [=====================

In [23]:
json_mod = model.to_json()
#Saving the model weights
with open('model_VGG16.json','w') as file:
    file.write(json_mod)
model.save_weights('model_VGG16.h5')

In [13]:
print(y_train)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


In [28]:
y_pred = model.predict(X_test)

In [16]:
y_pred.shape

(10000, 10)

In [25]:
import numpy as np
y_final = [ np.argmax( y_pred[i] ) for i in range(n_test) ]

In [26]:
y_val = list(map(int,y_test))

In [30]:
np.sum(np.array(y_final) == np.array(y_val) ) /n_test 

0.62

#### Final Result
    - Train Accuracy = 74.4 %
    - Test Accuracy = 62%